<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Document</title>
</head>
<body>
    
    <script>    
        const p = new Promise(function(resolve,reject){
        resolve(1);
        }).then(function(value){ // 第一个then // 1
        console.log(value);
        return value * 2;
        }).then(function(value){ // 第二个then // 2
        console.log(value);
        }).then(function(value){ // 第三个then // undefined
        console.log(value);
        return Promise.resolve('resolve'); 
        }).then(function(value){ // 第四个then // resolve
        console.log(value);
        return Promise.reject('reject'); 
        }).then(function(value){ // 第五个then //reject:reject
        console.log('resolve:' + value);
        }, function(err) {
        console.log('reject:' + err);
        });
    </script>

    <pre>
        demo1：============================================================================================
        const p = new Promise(function(resolve,reject){
            resolve('success');
        });
        
        p.then(function(value){
            console.log(value);
        });
        
        console.log('first');

        demo2：============================================================================================
        const p = new Promise(function(resolve,reject){
            resolve(1);
          }).then(function(value){ // 第一个then // 1
            console.log(value);
            return value * 2;
          }).then(function(value){ // 第二个then // 2
            console.log(value);
          }).then(function(value){ // 第三个then // undefined
            console.log(value);
            return Promise.resolve('resolve'); 
          }).then(function(value){ // 第四个then // resolve
            console.log(value);
            return Promise.reject('reject'); 
          }).then(function(value){ // 第五个then //reject:reject
            console.log('resolve:' + value);
          }, function(err) {
            console.log('reject:' + err);
          });
    </pre>
</body>
</html>


promise
    .then(...)    //返回一个新的promise，如果then之前的promise是rejected则延续
    .catch(...);    //又返回一个新的promise，如果catch之前的promise是resolved则延续

promise
    //返回一个新的promise
    //如果then之前的promise是resolved，则由第一个参数返回
    //如果then之前的promise是rejected，则由第二个参数返回。
    .then(..., ...);    

例子：
const fn = () => {
  throw 2;
}

//promise.then(...).catch(...);
Promise.resolve(1)         //{ [[PromiseStatus]]:"resolved", [[PromiseValue]]:1 }
  .then(v => {           //1
      fn();              //抛异常了，then返回一个rejected的promise
      return 3;          //后面不执行了
  })                     //{ [[PromiseStatus]]:"rejected", [[PromiseValue]]:2 }
  .catch(v => {          //v是throw的值2
      console.log(v);    //2
      return 4;          //catch返回一个resolved且值为4的promise
  });                    //{ [[PromiseStatus]]:"resolved", [[PromiseValue]]:4 }
//程序最后正常结束

//promise.then(..., ...);
Promise.resolve(1)         //{ [[PromiseStatus]]:"resolved", [[PromiseValue]]:1 }
  .then(
      v => {             //1
          fn();          //抛异常了，then返回一个rejected的promise
          return 3;      //后面不执行了
      },
      v => {             //这里只有then之前是rejected才执行
          console.log(v);//不执行
          return 4;      //不执行
      }
  );                     //{ [[PromiseStatus]]:"rejected", [[PromiseValue]]:2 }
//程序最后抛异常：Uncaught (in promise) 2    